type Info = {
  id?: string;
  profile: string;
  fname: string;
  lname: string;
  phone: string;
  birthday: string;
  work: string;
  relation: string;
  education: string;
  lives: string;
  story: string;
  facebook: string;
  instagram: string;
  whatsapp: string;
  linkedin: string;
  twitter: string;
  telegram: string;
};
export default Info;
